### ISSUE TITLE
Class 'Kordy\Ticketit\Models\Comment' not found

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#11] opened 2015-09-12 11:22 UTC
Hi!

I really don't know if this issue is related to your project or just my configuration is wrong. I'm just asking for your help, I don't have a clue what's causing this.

So after running `php artisan clear-compiled` I *always* get the following error message:

```
> php artisan clear-compiled
PHP Fatal error:  Class 'Kordy\Ticketit\Models\Comment' not found in /var/www/vendor/kordy/ticketit/src/TicketitServiceProvider.php on line 33


                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Kordy\Ticketit\Models\Comment' not found          
                                                           


Script php artisan clear-compiled handling the post-update-cmd event returned with an error


                                                                                                                                                                           
  [RuntimeException]                                                                                                                                                       
  Error Output: PHP Fatal error:  Class 'Kordy\Ticketit\Models\Comment' not found in /var/www/vendor/kordy/ticketit/src/TicketitServiceProvider.php on line 33       

```

After this when I try to run *any* page I get the above error.

To solve this, I usually do the following:

I comment out the service provider from my `config/app.php` file:

```
//Kordy\Ticketit\TicketitServiceProvider::class,
```
Then I run 

```
$ php artisan clear-compiled
$ php artisan optimize
```

Then I remove the comment from `config/app.php`:

```
Kordy\Ticketit\TicketitServiceProvider::class,
```

After these steps, everything works. But after a while it's a bit inconvenient. 

Can you suggest something, what could I do?

**Comment by thekordy** [comment] 2015-09-12 11:45
I could not regenerate the error, following the standard way of installing and removing the package

Install:
1. composer require kordy/ticketit
2. add Kordy\Ticketit\TicketitServiceProvider::class, to app.php config

Removing:
1. remove Kordy\Ticketit\TicketitServiceProvider::class, from app.php config
2. composer remove kordy/ticketit


```
vagrant@homestead:~/Code/ticketit2$ composer remove kordy/ticketit
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing kordy/ticketit (v0.0.5)
Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
vagrant@homestead:~/Code/ticketit2$ php artisan clear-compile
vagrant@homestead:~/Code/ticketit2$ php artisan optimize
Generating optimized class loader
vagrant@homestead:~/Code/ticketit2$ composer require kordy/ticketit
Using version ^0.0.5 for kordy/ticketit
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing kordy/ticketit (v0.0.5)
    Loading from cache

Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader
vagrant@homestead:~/Code/ticketit2$ 

```

**Comment by balping** [comment] 2015-09-12 11:46
Yeah, I tried removing and re-installing many times... Anyway, thanks. Probably something's wrong at my side

**Comment by thekordy** [comment] 2015-09-12 11:59
As a rule for me, I always remove/comment the package service provider class in the app.php before updating the auto load (either installing or removing).

So before i install or remove ticketit package, i have to remove its service provider class from the app.php file. 
And so for all other packages, remove their service provider class from app.php when you are going to install or remove them.

**Comment by balping** [comment] 2015-09-12 12:00
Ok, thanks for your advice

**Comment by FusionDesign** [comment] 2015-09-24 05:38
Same thing here. Tried fixing it myself. Removed / reinstalled a ton of times a bunch of different ways.

**Comment by thekordy** [comment] 2015-09-24 08:54
First before install or uninstall, make sure you removed this line from config/app.php file
'''php
Kordy\Ticketit\TicketitServiceProvider::class,
'''
Then follow the installation or uninstall instructions

**Comment by FusionDesign** [comment] 2015-09-25 05:42
It was all working perfect. Try running composer update or composer dump-autoload on a fresh project. It breaks again.

**Comment by FusionDesign** [comment] 2015-09-26 00:12
So here's what I've done:
1. Forked the package to my local dev machine.
2. Used (https://github.com/Jeroen-G/laravel-packager) to set up a brand new package.
3. Ported your package into the folder structure provided and renamed all folder references to case-sensitive PSR-4 references (lowercase to sentence case). (eg. referencing Kordy\Ticketit\Models when the folder name is "models").

I attempted to composer update and break the package but nothing seems to be breaking it. The issue is: I've already converted all views to MaterializeCSS. If you'd like, I can port your original revisions to a proper namespace and it should fix this issue. I've not seen it come up again since forking.

Let me know and I'll go ahead and fork a Bootstrap version PR.

**Comment by thekordy** [comment] 2015-09-26 19:23
Hello,

To be honest, I couldn't regenerate the error you had. Would you please mention how do you install the package? and if you uses the composer install or just cloning the package?

For the idea of using styling frameworks, I think we should work in ways that we always can integrate with the user current project styling, if we made our own style, then we won't be able to integrate.

Although, I like what you did, this way the package is more compliant to PSR-4, I appreciate your work :+1:

**Comment by FusionDesign** [comment] 2015-09-26 21:01
This should be all resolved with the latest PR. Let me know if any problems still persist. I'll be doing a fresh install on the preview URL tonight at 3am so I can verify all is well.

**Comment by thekordy** [comment] 2015-09-26 21:02
Thank you

**Comment by balping** [comment] 2015-09-26 21:03
Thank you guys for fixing this

**Closed by thekordy** 2015-09-26 21:02 UTC
Labels: question

**Comment by FusionDesign** [comment] 2015-09-26 21:10
No problem! Like I told Kordy -- I use this on my main website for my few clients I freelance for so I thank you more for releasing a modular way for me to move ticket systems around.
